# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java
pool:
  vmImage: macos-latest

parameters:
  - name: MSISDN
    displayName: MSISDN
    type: string
    default: 447775357449
  - name: SERVER
    displayName: SERVER
    type: string
    default: LIVE
    values:
      - QC1
      - QC2
      - QCX
      - INT1
      - PRODSUP
      - LIVE
  - name: UFL
    displayName: UFL
    type: string
    default: 3G
    values:
      - 3G
      - WIFI
  - name: username
    displayName: Username
    type: string
    default: 7062754530
  - name: password
    displayName: Password
    type: string
    default: Testing@1
  - name: APIURL
    displayName: API URL
    type: string
    default: https://mvax.vodafone.co.uk
    values:
      - https://mvax.dx-qcx-common.digital.vodafoneaws.co.uk
      - https://mvax.dx-qc1-common.digital.vodafoneaws.co.uk
      - https://mvax.dx-prodsup-common.digital.vodafoneaws.co.uk
      - https://mvax.dx-qc2-common.digital.vodafoneaws.co.uk
      - https://mvax.dx-int1-common.digital.vodafoneaws.co.uk
      - https://mvax.vodafone.co.uk
  - name: accountId
    displayName: Account Id
    type: string
    default: 7062754530
  - name: SubscriptionType
    displayName: Subscription Type
    type: string
    default: MPS
    values:
      - MPS
      - MBB
      - FLN
      - BB
  - name: Segment
    displayName: Segment
    type: string
    default: CONSUMER
    values:
      - CONSUMER
      - PREPAY
      - SMB
      - SOLETRADER
  - name: ReinventServer
    displayName: Reinvent Server
    type: string
    default: false
    values:
      - true
      - false
  - name: TCC
    displayName: TCC
    type: string
    default: TCC6
  - name: NeedTcc
    displayName: Need TCC
    type: string
    default: false
    values:
      - true
      - false
  - name: FirstName
    displayName: FirstName
    type: string
    default: MVA
  - name: LastName
    displayName: LastName
    type: string
    default: CP Testing
  - name: DeviceUID
    displayName: DeviceUID
    type: string
    default: fe63c741-0e49-49a9-bc9c-4d4e78a00eee
  - name: AppVersion
    displayName: App Version
    type: string
    default: 10.52
  - name: OSVersion
    displayName: OS Version
    type: string
    default: 11.3
  - name: USERTYPEPIPELINE
    displayName: User Type Pipeline
    type: string
    default: "@PAYG"
    values:
      - "@MPS"
      - "@MBB"
      - "@SMB"
      - "@SOLETRADER"
      - "@PAYG"
      - "@RED"
      - "@BVB"
      - "@BINGO"
      - "@PAYM"
      - "@PAYG1"
      - "@UNKNOWN_USER"
  - name: TESTTYPEPIPELINE
    displayName: Test Type Pipeline
    type: string
    default: "@REGRESSION"
    values:
      - "@REGRESSION"
      - "@SANITY"
      - "@paygDVT"
      - "@paymDVT"
      - "@childDVT"
      - "@CCS"
  - name: UFLTAGPIPELINE
    displayName: UFL Type Pipeline
    type: string
    default: "@3G"
    values:
      - "@3G"
      - "@WIFI"
  - name: LOGINPIPELINE
    displayName: Login Condition Pipeline
    type: string
    default: "not @LOGIN"
    values:
      - "not @LOGIN"
      - "@LOGIN"
  - name: DXIDMPIPELINE
    displayName: DXIDM Condition Pipeline
    type: string
    default: "not @DXIDM"
    values:
      - "not @DXIDM"
      - "@DXIDM"
  - name: SPECIALPIPELINE
    displayName: SPECIAL Condition Pipeline
    type: string
    default: "not @Special"
    values:
      - "not @Special"
      - "@Special"
  - name: UNKNOWN
    displayName: UNKNOWN user
    type: string
    default: false
    values:
      - false
      - true
  - name: DEVICE_NAME
    displayName: Device name
    type: string
    default: Samsung Galaxy S22 Ultra
  - name: PLATFORM_VERSION
    displayName: OS version
    type: string
    default: 12.0
  - name: BSUserName
    displayName: Browser Stack User Name
    type: string
    default: nehalabdelwahab_dGV9p0
  - name: BSAccessKey
    displayName: Browser Stack Access Key
    type: string
    default: jaFscKqrqdQhVjkkUBgM
  - name: BSAppURl
    displayName: Browser Stack App URL
    type: string
    default: bs://e0fc13952ebba68e9bf3dbc9ef80cdc57ea3e222
  - name: BSBuildName
    displayName: Browser Stack Build Name
    type: string
    default: build name
  - name: BSBuildNumber
    displayName: Browser Stack Build Number
    type: string
    default: build name
  - name: PLisLiveTest
    displayName: Production Flag
    type: string
    default: false
    values:
      - false
      - true
  - name: PLPINFlag
    displayName: Pin flag
    type: string
    default: true
    values:
      - false
      - true


stages:
  - stage:
    jobs:
      - job:
        workspace:
          clean: all
        condition: eq(variables['Build.Reason'], 'Manual')
        timeoutInMinutes: 200
        displayName: Android Run
        steps:
          - checkout: self
            fetchDepth: 1
            clean: true
          - task: NodeTool@0
            displayName: Setup Node
            inputs:
              versionSpec: 10.x
          - task: Bash@3
            displayName: Setup Bash Script
            inputs:
              targetType: inline
              script: >-
                npm install -g appium@1.19.1

                npm install wd

                appium&

                npm install -g allure-commandline

                npm install bestzip -g
          - task: JavaToolInstaller@0
            inputs:
              versionSpec: '17'
              jdkArchitectureOption: 'x64'
              jdkSourceOption: 'PreInstalled'
          - task: CmdLine@2
            displayName: Test Run
            inputs:
              script: >
                mvn clean install -Dcucumber.filter.tags="${{ parameters.TESTTYPEPIPELINE }} and ${{ parameters.USERTYPEPIPELINE }} and ${{ parameters.UFLTAGPIPELINE }} and ${{ parameters.LOGINPIPELINE }} and ${{ parameters.DXIDMPIPELINE }} and ${{ parameters.SPECIALPIPELINE }}" -DSERVER="${{ parameters.SERVER }}" -DPLATFORM="android" -DMSISDN="${{ parameters.MSISDN }}" -DUFL="${{ parameters.UFL }}" -DREMOTE="false" -Durl="${{ parameters.APIURL }}" -Dusername="${{ parameters.username }}" -Dpassword="${{ parameters.password }}" -DaccountId="${{ parameters.accountId }}" -DSubscriptionType="${{ parameters.SubscriptionType }}" -DSegment="${{ parameters.Segment }}" -DReinventServer="${{ parameters.ReinventServer }}" -DTCC="${{ parameters.TCC }}" -DNeedTcc="${{ parameters.NeedTcc }}" -DAppVersion="${{ parameters.AppVersion }}" -DOSVersion="${{ parameters.OSVersion }}" -DUnknownUser="${{ parameters.UNKNOWN }}" -DDEVICE_NAME="${{ parameters.DEVICE_NAME }}" -DPLATFORM_VERSION="${{ parameters.PLATFORM_VERSION }}" -DbrowserStackRun="True" -DbrowserStackUserName="${{ parameters.BSUserName }}" -DbrowserStackAccessKey="${{ parameters.BSAccessKey }}" -DappUrl="${{ parameters.BSAppURl }}" -DbuildName="${{ parameters.BSBuildName }}" -DbuildNumber="${{ parameters.BSBuildNumber }}" -DisLiveTest="${{ parameters.PLisLiveTest }}" -DDeviceUID="${{ parameters.DeviceUID }}"

  - stage:
    jobs:
      - job: envCheck
        strategy:
          matrix:
            EnvCheck-INT1:
              MSISDN: 447879008831
              UFL: 3G
              SERVER: int1
              username: 362826783
              accountId: 7001233789
              AppVersion: 10.45
              SubscriptionType: MPS
              Segment: CONSUMER
              Reinvent_Server: false
              TCC: TCC6
              Need_Tcc: false
              APIURL: https://mvax.dx-int1-common.digital.vodafoneaws.co.uk
              OSVersion: 12.0
              UNKNOWN: false
              DEVICE_NAME: Google Pixel 7
              PLATFORM_VERSION: 13.0
              Build_Number: int1
              PLisLiveTest: false
            EnvCheck-QC1:
              MSISDN: 447867602837
              UFL: 3G
              SERVER: qc1
              username: AUTOMATION123717122
              accountId: 7051396926
              AppVersion: 10.45
              SubscriptionType: MBB
              Segment: CONSUMER
              Reinvent_Server: false
              TCC: TCC7
              Need_Tcc: false
              APIURL: https://mvax.dx-qc1-common.digital.vodafoneaws.co.uk
              OSVersion: 9
              UNKNOWN: false
              DEVICE_NAME: Google Pixel 3
              PLATFORM_VERSION: 9.0
              Build_Number: qc1
              PLisLiveTest: false
            EnvCheck-QC2:
              MSISDN: 447879008831
              UFL: 3G
              SERVER: qc2
              username: 362826783
              accountId: 7001233789
              AppVersion: 10.45
              SubscriptionType: MPS
              Segment: CONSUMER
              Reinvent_Server: false
              TCC: TCC8
              Need_Tcc: false
              APIURL: https://mvax.dx-qc2-common.digital.vodafoneaws.co.uk
              OSVersion: 9
              UNKNOWN: false
              DEVICE_NAME: Google Pixel 5
              PLATFORM_VERSION: 12.0
              Build_Number: qc2
              PLisLiveTest: false
            EnvCheck-QCX:
              MSISDN: 447867602837
              UFL: 3G
              SERVER: qcx
              username: AUTOMATION123717122
              accountId: 7051396926
              AppVersion: 10.45
              SubscriptionType: MPS
              Segment: CONSUMER
              Reinvent_Server: false
              TCC: TCC6
              Need_Tcc: false
              APIURL: https://mvax.dx-qcx-common.digital.vodafoneaws.co.uk
              OSVersion: 9
              UNKNOWN: false
              DEVICE_NAME: Google Pixel 3
              PLATFORM_VERSION: 10.0
              Build_Number: qcx
              PLisLiveTest: false
            EnvCheck-PRODSUP:
              MSISDN: 447867607327
              UFL: 3G
              SERVER: ProdSup
              username: ABC1221
              accountId: 7001246564
              AppVersion: 10.45

              SubscriptionType: MPS
              Segment: SMB
              Reinvent_Server: true
              TCC: TCC9
              Need_Tcc: true
              APIURL: https://mvax.dx-prodsup-common.digital.vodafoneaws.co.uk
              OSVersion: 9
              UNKNOWN: false
              DEVICE_NAME: Google Pixel 6 Pro
              PLATFORM_VERSION: 13.0
              Build_Number: prodsup
              PLisLiveTest: false
          maxParallel: 3
        workspace:
          clean: all
        condition: eq(variables['Build.Reason'], 'Schedule')
        timeoutInMinutes: 200
        displayName: Android Run
        steps:
          - checkout: self
            fetchDepth: 1
            clean: true
          - task: NodeTool@0
            displayName: Setup Node
            inputs:
              versionSpec: 10.x
          - task: Bash@3
            displayName: Setup Bash Script
            inputs:
              targetType: inline
              script: >-
                npm install -g appium@1.19.1

                npm install wd

                appium&

                npm install -g allure-commandline

                npm install bestzip -g
          - task: JavaToolInstaller@0
            inputs:
              versionSpec: '17'
              jdkArchitectureOption: 'x64'
              jdkSourceOption: 'PreInstalled'
          - task: CmdLine@2
            displayName: Test Run
            inputs:
              script: >
                echo "$(AppVersion)"

                mvn clean install -Dcucumber.filter.tags="@EnvChecks" -DSERVER="$(SERVER)" -DPLATFORM="Android" -DMSISDN="$(MSISDN)" -DUFL="$(UFL)" -DREMOTE="false" -Durl="$(APIURL)" -Dusername="$(username)" -DaccountId="$(accountId)" -DLOA3AccountId="$(accountId)" -DSubscriptionType="$(SubscriptionType)" -DSegment="$(Segment)" -DReinventServer="$(ReinventServer)" -DTCC="$(TCC)" -DNeedTcc="$(NeedTcc)" -DAppVersion="$(AppVersion)" -DOSVersion="$(OSVersion)" -DUnknownUser="$(UNKNOWN)" -DDEVICE_NAME="$(DEVICE_NAME)" -DPLATFORM_VERSION="$(PLATFORM_VERSION)" -DbrowserStackRun="True" -DbrowserStackUserName="yarahelal_XQJnIN" -DbrowserStackAccessKey="R9vAwdw5zpizUCRi2zVq" -DappUrl="bs://a2c64530fe2dd5e5280a5b629bfbf7fcc03554c9" -DbuildName="Scheduled env chck run" -Dpassword="testing1" -DbuildNumber="$(Build_Number)" -DisLiveTest="$(PLisLiveTest)"


          - task: PublishTestResults@2
            inputs:
              testResultsFormat: 'JUnit'
              testResultsFiles: 'Cucumber.xml'
              searchFolder: '$(System.DefaultWorkingDirectory)'
              testRunTitle: 'MVA App Automation Run'
              publishRunAttachments: true
              failTaskOnFailedTests: true

          - task: PowerShell@2
            inputs:
              targetType: 'inline'
              script: |
                $myTeamsWebHook = “https://vodafone.webhook.office.com/webhookb2/4b23d8c8-e5e2-4935-afe9-368b6b0f16ae@68283f3b-8487-4c86-adb3-a5228f18b893/IncomingWebhook/03c7cbb2d4364a4882b5ae6dbf1e3c12/285dcd38-f1ee-4d88-8282-0777915167c4”
                Invoke-RestMethod -Method post -ContentType 'Application/Json' -Body '{"text":"$(SERVER) is working fine"}' -Uri $myTeamsWebHook
            condition: Succeeded()

          - task: PowerShell@2
            inputs:
              targetType: 'inline'
              script: |
                $myTeamsWebHook = “https://vodafone.webhook.office.com/webhookb2/4b23d8c8-e5e2-4935-afe9-368b6b0f16ae@68283f3b-8487-4c86-adb3-a5228f18b893/IncomingWebhook/03c7cbb2d4364a4882b5ae6dbf1e3c12/285dcd38-f1ee-4d88-8282-0777915167c4”
                Invoke-RestMethod -Method post -ContentType 'Application/Json' -Body '{"text":"$(SERVER) is Down/Partially Failing"}' -Uri $myTeamsWebHook
            condition: Failed()


schedules:
  - cron: "0 8 * * 0-4"
    displayName: Daily Morning Env check
    branches:
      include:
        - Release/R30